[global]
disableWatchdogWarning = true

[client]
showErrorDetails = false
toolbarMode = "minimal"

[runner]
fastReruns = true

[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
